<Project>
  <PropertyGroup>
    <SCPSLManagedPath>D:\SteamLibrary\steamapps\common\SCP Secret Laboratory Dedicated Server\SCPSL_Data\Managed</SCPSLManagedPath>
  </PropertyGroup>
  
  <ItemGroup>
    <!-- Core game assemblies -->
    <Reference Include="Assembly-CSharp">
      <HintPath>$(SCPSLManagedPath)\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>$(SCPSLManagedPath)\Assembly-CSharp-firstpass.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(SCPSLManagedPath)\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(SCPSLManagedPath)\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(SCPSLManagedPath)\UnityEngine.PhysicsModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(SCPSLManagedPath)\UnityEngine.TextRenderingModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Mirror">
      <HintPath>$(SCPSLManagedPath)\Mirror.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Mirror.Components">
      <HintPath>$(SCPSLManagedPath)\Mirror.Components.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="NorthwoodLib">
      <HintPath>$(SCPSLManagedPath)\NorthwoodLib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="CommandSystem.Core">
      <HintPath>$(SCPSLManagedPath)\CommandSystem.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="LabApi">
      <HintPath>$(SCPSLManagedPath)\LabApi.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Pooling">
      <HintPath>$(SCPSLManagedPath)\Pooling.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
